/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class PVotaciones extends javax.swing.JFrame {

    /**
     * Creates new form PVotaciones
     */
    boolean personeros = false;
    boolean reprecentante = false;

    public PVotaciones() {
        initComponents();
        try {
            Imagen img = new Imagen("/Imagenes/descarga.jpg", jPanel3.getWidth(), jPanel3.getHeight());
            Imagen img1 = new Imagen("/Imagenes/descarga1.jpg", jPanel4.getWidth(), jPanel4.getHeight());
            Imagen img2 = new Imagen("/Imagenes/descarga2.jpg", jPanel5.getWidth(), jPanel5.getHeight());
            Imagen img3 = new Imagen("/Imagenes/descarga3.jpg", jPanel6.getWidth(), jPanel6.getHeight());
            Imagen img4 = new Imagen("/Imagenes/descarga4.jpg", jPanel7.getWidth(), jPanel7.getHeight());
            Imagen img5 = new Imagen("/Imagenes/descarga5.jpg", jPanel8.getWidth(), jPanel8.getHeight());
            Imagen img6 = new Imagen("/Imagenes/descarga6.jpg", jPanel9.getWidth(), jPanel9.getHeight());
            Imagen img7 = new Imagen("/Imagenes/descarga7.jpg", jPanel10.getWidth(), jPanel10.getHeight());
            Imagen img11 = new Imagen("/Imagenes/descarga8.jpg", jPanel11.getWidth(), jPanel11.getHeight());
            Imagen img9 = new Imagen("/Imagenes/panit.jpg", getWidth(), getHeight());
//            Imagen img10 = new Imagen("/Imagenes/hojas.jpg", jPanel1.getWidth(), jPanel1.getHeight());
//
//            jPanel1.add(img10);
            jPanel3.add(img);
            jPanel4.add(img1);
            jPanel5.add(img2);
            jPanel6.add(img3);
            jPanel7.add(img4);
            jPanel8.add(img5);
            jPanel9.add(img6);
            jPanel10.add(img7);
            jPanel11.add(img11);
            add(img9);
        } catch (Exception io) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, hay archivos faltanates");
        }

        repaint();
        setResizable(false);
        setLocationRelativeTo(null);
//        com.sun.awt.AWTUtilities.setWindowOpaque(jPanel1., 0.5f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personero", 0, 0, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton3.setText("Elegir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Elegir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Elegir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Elegir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Elegir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Elegir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("              01");

        jLabel2.setText("              05");

        jLabel3.setText("        Blanco");

        jLabel4.setText("              02");

        jLabel5.setText("              03");

        jLabel6.setText("               04");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Representante", 0, 0, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("Elegir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Elegir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("             01");

        jLabel8.setText("              02");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel9.setText("       Blanco");

        jButton9.setText("Elegir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel2.getComponents().length; i++) {
                jPanel2.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("R1")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }
            if (personeros) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                reprecentante = true;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel2.getComponents().length; i++) {
                jPanel2.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("R2")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }
            if (personeros) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                reprecentante = true;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel1.getComponents().length; i++) {
                jPanel1.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("P6")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }

            if (reprecentante) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                personeros = true;
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel1.getComponents().length; i++) {
                jPanel1.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("P5")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }

            if (reprecentante) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                personeros = true;
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel1.getComponents().length; i++) {
                jPanel1.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("P4")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }

            if (reprecentante) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                personeros = true;
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel1.getComponents().length; i++) {
                jPanel1.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("P3")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }

            if (reprecentante) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                personeros = true;
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel1.getComponents().length; i++) {
                jPanel1.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("P2")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }
            if (reprecentante) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                personeros = true;
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel1.getComponents().length; i++) {
                jPanel1.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("P1")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }
            if (reprecentante) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
                System.out.println("smdlmflñdmfld");
            } else {
                personeros = true;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int show = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Estás totalmente seguro de elegir a ésta persona?", "Warning", show);
        if (dialogResult == 0) {
            for (int i = 0; i < jPanel2.getComponents().length; i++) {
                jPanel2.getComponent(i).setEnabled(false);
            }
            JOptionPane.showMessageDialog(null, "Voto Registrado");
            try {
                File arc = new File("C:\\Industrial");
                if (arc.exists() == false) {
                    arc.mkdir();
                }
                String numero = "C:\\Industrial\\Votos.txt";
                File archivo = null;
                FileReader fr = null;
                BufferedReader br = null;
                FileWriter fichero = null;
                PrintWriter pw = null;
                String linea = "";
                String finali[] = new String[100000];
                boolean validation = false;
                try {
                    archivo = new File(numero);
                    fr = new FileReader(archivo);
                    br = new BufferedReader(fr);
                    int num = 0;

                    while (true) {
                        linea = br.readLine();
                        if (linea == null) {
                            break;
                        }
                        String tamporal[] = linea.split(" ");
                        if (tamporal[0].equals("R3")) {
                            int nnnn = Integer.parseInt(tamporal[1].toString());
                            nnnn++;
                            finali[num] = tamporal[0] + " " + nnnn;
                            num++;
                        } else {
                            finali[num] = tamporal[0] + " " + tamporal[1];
                        }
                        tamporal = null;
                        num++;
                    }
                    br.close();
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (null != fr) {
                            fr.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
                //hasta aquí es la lactra

                //escritura
                try {
                    fichero = new FileWriter(numero);
                    pw = new PrintWriter(fichero);
                    for (int i = 0; i < finali.length; i++) {
                        if (finali[i] != null) {
                            pw.append(finali[i]);
                            pw.println();
                        }
                    }
                    fichero.close();
                } catch (Exception e) {
                    System.out.println("hola");
                } finally {
                    try {
                        if (null != fichero) {
                            fichero.close();
                        }
                    } catch (Exception e2) {
                        e2.printStackTrace();
                    }
                }
            } catch (Exception io) {
                JOptionPane.showMessageDialog(null, "Es posible que no esté debidamente ingresada la basde de datos, si es ése el caso, recomendamos que la ingrese.");
            }
            if (personeros) {
                dispose();
                Login lg = new Login();
                lg.setVisible(true);
            } else {
                reprecentante = true;
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PVotaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PVotaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PVotaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PVotaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PVotaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
